<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdf18d84772c710382f72d4c9bab7efd2
{
    public static $files = array (
        '7745382c92b7799bf1294b1f43023ba2' => __DIR__ . '/..' . '/tracy/tracy/src/shortcuts.php',
        '2c102faa651ef8ea5874edb585946bce' => __DIR__ . '/..' . '/swiftmailer/swiftmailer/lib/swift_required.php',
    );

    public static $prefixesPsr0 = array (
        'T' =>
        array (
            'Twig_' =>
            array (
                0 => __DIR__ . '/..' . '/twig/twig/lib',
            ),
        ),
        'S' =>
        array (
            'Symfony\\Component\\Console\\' =>
            array (
                0 => __DIR__ . '/..' . '/symfony/console',
            ),
        ),
        'C' =>
        array (
            'Cygnite' =>
            array (
                0 => __DIR__ . '/..' . '/cygnite/framework/src',
            ),
        ),
    );

    public static $classMap = array (
        'Application\\Components\\Authentication\\Auth' => __DIR__ . '/../..' . '/apps/components/authentication/Auth.php',
        'Apps\\Components\\Form\\ProductForm'           => __DIR__ . '/../..' . '/apps/components/form/ProductForm.php',
        'Apps\\Controllers\\AdminController'            => __DIR__ . '/../..' . '/apps/controllers/AdminController.php',
        'Apps\\Controllers\\AuthController'             => __DIR__ . '/../..' . '/apps/controllers/AuthController.php',
        'Apps\\Controllers\\HomeController'             => __DIR__ . '/../..' . '/apps/controllers/HomeController.php',
        'Apps\\Controllers\\ProductController'          => __DIR__ . '/../..' . '/apps/controllers/ProductController.php',
        'Apps\\Extensions\\Api'                         => __DIR__ . '/../..' . '/apps/extensions/Api.php',
        'Apps\\Extensions\\General'                     => __DIR__ . '/../..' . '/apps/extensions/General.php',
        'Apps\\Extensions\\GeneralInterface'            => __DIR__ . '/../..' . '/apps/extensions/GeneralInterface.php',
        'Array2XML'                                     => __DIR__ . '/../..' . '/apps/extensions/Array2XML.php',
        'Apps\\Models\\Product'                         => __DIR__ . '/../..' . '/apps/models/Product.php',
        'Apps\\Models\\User'                            => __DIR__ . '/../..' . '/apps/models/User.php',
        'Tracy\\Bar'                                    => __DIR__ . '/..' . '/tracy/tracy/src/Tracy/Bar.php',
        'Tracy\\BlueScreen'                             => __DIR__ . '/..' . '/tracy/tracy/src/Tracy/BlueScreen.php',
        'Tracy\\Debugger'                               => __DIR__ . '/..' . '/tracy/tracy/src/Tracy/Debugger.php',
        'Tracy\\DefaultBarPanel'                        => __DIR__ . '/..' . '/tracy/tracy/src/Tracy/DefaultBarPanel.php',
        'Tracy\\Dumper'                                 => __DIR__ . '/..' . '/tracy/tracy/src/Tracy/Dumper.php',
        'Tracy\\FireLogger'                             => __DIR__ . '/..' . '/tracy/tracy/src/Tracy/FireLogger.php',
        'Tracy\\Helpers'                                => __DIR__ . '/..' . '/tracy/tracy/src/Tracy/Helpers.php',
        'Tracy\\IBarPanel'                              => __DIR__ . '/..' . '/tracy/tracy/src/Tracy/IBarPanel.php',
        'Tracy\\Logger'                                 => __DIR__ . '/..' . '/tracy/tracy/src/Tracy/Logger.php',
        'Tracy\\OutputDebugger'                         => __DIR__ . '/..' . '/tracy/tracy/src/Tracy/OutputDebugger.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInitdf18d84772c710382f72d4c9bab7efd2::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitdf18d84772c710382f72d4c9bab7efd2::$classMap;

        }, null, ClassLoader::class);
    }
}
