<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Application\\Components\\Authentication\\Auth' => $baseDir . '/apps/components/authentication/Auth.php',
    'Apps\\Components\\Form\\ProductForm'           => $baseDir . '/apps/components/form/ProductForm.php',
    'Apps\\Controllers\\AdminController'            => $baseDir . '/apps/controllers/AdminController.php',
    'Apps\\Controllers\\AuthController'             => $baseDir . '/apps/controllers/AuthController.php',
    'Apps\\Controllers\\HomeController'             => $baseDir . '/apps/controllers/HomeController.php',
    'Apps\\Controllers\\ProductController'          => $baseDir . '/apps/controllers/ProductController.php',
    'Apps\\Extensions\\Api'                         => $baseDir . '/apps/extensions/Api.php',
    'Apps\\Extensions\\General'                     => $baseDir . '/apps/extensions/General.php',
    'Apps\\Extensions\\GeneralInterface'            => $baseDir . '/apps/extensions/GeneralInterface.php',
    'Array2XML'                                     => $baseDir . '/apps/extensions/Array2XML.php',
    'Apps\\Models\\Product'                         => $baseDir . '/apps/models/Product.php',
    'Apps\\Models\\User'                            => $baseDir . '/apps/models/User.php',
    'Tracy\\Bar'                                    => $vendorDir . '/tracy/tracy/src/Tracy/Bar.php',
    'Tracy\\BlueScreen'                             => $vendorDir . '/tracy/tracy/src/Tracy/BlueScreen.php',
    'Tracy\\Debugger'                               => $vendorDir . '/tracy/tracy/src/Tracy/Debugger.php',
    'Tracy\\DefaultBarPanel'                        => $vendorDir . '/tracy/tracy/src/Tracy/DefaultBarPanel.php',
    'Tracy\\Dumper'                                 => $vendorDir . '/tracy/tracy/src/Tracy/Dumper.php',
    'Tracy\\FireLogger'                             => $vendorDir . '/tracy/tracy/src/Tracy/FireLogger.php',
    'Tracy\\Helpers'                                => $vendorDir . '/tracy/tracy/src/Tracy/Helpers.php',
    'Tracy\\IBarPanel'                              => $vendorDir . '/tracy/tracy/src/Tracy/IBarPanel.php',
    'Tracy\\Logger'                                 => $vendorDir . '/tracy/tracy/src/Tracy/Logger.php',
    'Tracy\\OutputDebugger'                         => $vendorDir . '/tracy/tracy/src/Tracy/OutputDebugger.php'
);
