<?php
namespace Apps\Models;

use Cygnite\Foundation\Application;
use Cygnite\Database\Schema;
use Cygnite\Common\UrlManager\Url;
use Cygnite\Database\ActiveRecord;
use Cygnite\Common\Pagination;

/**
* This file is generated by Cygnite CLI Crud generator
*/

class Intro extends ActiveRecord
{
    //your database connection name
    // protected $database = 'cygnite';

    protected $tableName = 'intro';

    protected $primaryKey = 'id';

    public $perPage = 5;

    public function __construct()
    {
        parent::__construct();
    }

    // used for pagination
    public function pageLimit()
    {
        return Url::segment($this->params['start_segment'] + 3);
    }

}// End of the User Model